version: '3'

services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    links:
      - mongo
    environment:
      ROOT_URL: ${APP_ROOT_URL:-http://localhost}
      MONGO_URL: mongodb://mongo:27017/meteor
      PORT: 3000

  mongo:
    image: mongo:latest
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db

volumes:
  data:
  
# version: "3"
# services:
#   app:
#     container_name: fwb-app
#     restart: always
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "3000:3000"
#     links:
#       - mongo
#     environment:
#       ROOT_URL: ${APP_ROOT_URL:-http://localhost}
#       MONGO_URL: mongodb://mongo:27017/meteor
#       PORT: 3000
#   mongo:
#     container_name: mongo
#     image: mongo
#     volumes:
#       - ./data:/data/db
#     ports:
#       - "27017:27017"